# CityBikes

Send a request to CityBikes for the city of your choice.

In [9]:
#import libraries
import requests
import os
import pandas as pd

# http://api.citybik.es/v2/    API bike website

In [10]:
# Create dictionary for headers
headers = {"Accept": "application/json"}
city_url = 'http://api.citybik.es/v2/networks/citi-bike-miami'

#Python GET request to citybikes API.
miami = requests.get(city_url, headers=headers)

#See if GET response is sucessful 
print(miami)

<Response [200]>

Parse through the response to get the details you want for the bike stations in that city (latitude, longitude, number of bikes).

In [11]:
#Get the json 
miami_json = miami.json()

In [14]:
#Parse miami stations
miami_stations = miami_json["network"]["stations"]

#Go through each station and get latitude, longitude, bikes 
def station_iterate(miami_stations):
    latitude= []
    longitude= []
    bikes = []
    for station in miami_stations:
            latitude.append(station['latitude'])
            longitude.append(station['longitude'])
            bikes.append(station['free_bikes'])
    return latitude, longitude, bikes

station_iterate(miami_stations)

([25.729275,
  25.732522,
  25.7511,
  25.760082,
  25.761884,
  25.768483,
  25.761522,
  25.7604,
  25.7603626,
  25.767414,
  25.765769,
  25.779881,
  25.767497,
  25.76258,
  25.76589,
  25.771428,
  25.7717329,
  25.7725576,
  25.77369,
  25.7733724,
  25.7870287,
  25.7883347,
  25.789722,
  25.78974,
  25.79274,
  25.794895,
  25.7999106,
  25.801,
  25.80533,
  25.7799583,
  25.7984785,
  25.8022384,
  25.8014206,
  25.8025414,
  25.775986,
  25.775019,
  25.7926049,
  25.747976,
  25.777171,
  25.7729842,
  25.782258,
  25.784943,
  25.770155,
  25.755818,
  25.765327,
  25.767379,
  25.769435,
  25.769775,
  25.7711036,
  25.770722,
  25.772132,
  25.773511,
  25.772677,
  25.774917,
  25.77679,
  25.779172,
  25.780759,
  25.78247,
  25.785034,
  25.7874891,
  25.776876,
  25.777061,
  25.77581,
  25.775684,
  25.774795,
  25.776039,
  25.779273,
  25.779413,
  25.778413,
  25.77947,
  25.781921,
  25.780853,
  25.782184,
  25.782022,
  25.782745,
  25.783657,
  25.784238,
  25.784225,
  25.784078,
  25.785306,
  25.786483,
  25.785114,
  25.7851581,
  25.787059,
  25.788892,
  25.787298,
  25.787494,
  25.787603,
  25.787584,
  25.788726,
  25.790662,
  25.792726,
  25.790084,
  25.790149,
  25.789955,
  25.791498,
  25.791154,
  25.790727,
  25.7917516,
  25.79034,
  25.791421,
  25.793401,
  25.792573,
  25.794751,
  25.792316,
  25.794,
  25.798194,
  25.794822,
  25.795501,
  25.79523,
  25.796314,
  25.7968314,
  25.798538,
  25.800083,
  25.80087,
  25.802289,
  25.803857,
  25.806837,
  25.809047,
  25.812503,
  25.814342,
  25.81215,
  25.816658,
  25.816011,
  25.820867,
  25.830375,
  25.84666,
  25.85069,
  25.854211,
  25.8558358,
  25.852079,
  25.857971,
  25.858234,
  25.861253,
  25.8642,
  25.873098,
  25.88108,
  25.8834214,
  25.8871218,
  25.887449,
  25.893302,
  25.777514,
  25.790462,
  25.854495,
  25.734206,
  25.730382,
  25.835972,
  25.8135937,
  25.8202417,
  25.827261,
  25.813662,
  25.7797147,
  25.7653626,
  25.7674054,
  25.8074771,
  25.830476,
  25.814942,
  25.8409532,
  25.8033602,
  25.8047295,
  25.8561371,
  25.7910019,
  25.7851991,
  25.7975825,
  25.77613,
  25.77662],
 [-80.241581,
  -80.233244,
  -80.202641,
  -80.196217,
  -80.193101,
  -80.190547,
  -80.1967748,
  -80.19186,
  -80.1936702,
  -80.199166,
  -80.211373,
  -80.218424,
  -80.195732,
  -80.193948,
  -80.191042,
  -80.190815,
  -80.1899646,
  -80.1921467,
  -80.18896,
  -80.1920071,
  -80.1939982,
  -80.1932528,
  -80.188952,
  -80.18622,
  -80.18646,
  -80.188672,
  -80.19544,
  -80.18888,
  -80.1891,
  -80.1955923,
  -80.2031538,
  -80.2014196,
  -80.1991306,
  -80.1948694,
  -80.18865,
  -80.196429,
  -80.1936645,
  -80.210054,
  -80.186888,
  -80.1860208,
  -80.189191,
  -80.18683,
  -80.198036,
  -80.196467,
  -80.131324,
  -80.135871,
  -80.133049,
  -80.13739,
  -80.1327318,
  -80.133801,
  -80.138313,
  -80.139686,
  -80.134644,
  -80.131584,
  -80.130943,
  -80.130828,
  -80.129913,
  -80.129882,
  -80.129455,
  -80.12955,
  -80.133941,
  -80.133155,
  -80.135887,
  -80.137184,
  -80.13842,
  -80.139648,
  -80.140007,
  -80.136161,
  -80.137229,
  -80.133392,
  -80.133056,
  -80.142166,
  -80.137565,
  -80.140846,
  -80.142005,
  -80.136329,
  -80.134101,
  -80.132476,
  -80.130798,
  -80.130966,
  -80.138603,
  -80.142562,
  -80.1432309,
  -80.143547,
  -80.143356,
  -80.140754,
  -80.135314,
  -80.132049,
  -80.130134,
  -80.134193,
  -80.131034,
  -80.132148,
  -80.133186,
  -80.134376,
  -80.135398,
  -80.136695,
  -80.137748,
  -80.138923,
  -80.1400728,
  -80.142303,
  -80.148155,
  -80.1444,
  -80.134979,
  -80.135571,
  -80.129287,
  -80.129013,
  -80.131951,
  -80.139358,
  -80.142951,
  -80.14138,
  -80.128517,
  -80.1274238,
  -80.128341,
  -80.127029,
  -80.125602,
  -80.125915,
  -80.129386,
  -80.125183,
  -80.123458,
  -80.123367,
  -80.129203,
  -80.135475,
  -80.130546,
  -80.123664,
  -80.122314,
  -80.122238,
  -80.12078,
  -80.120628,
  -80.120712,
  -80.1232378,
  -80.13755,
  -80.125305,
  -80.121002,
  -80.120704,
  -80.121223,
  -80.122093,
  -80.122207,
  -80.123717,
  -80.1219757,
  -80.133323,
  -80.132423,
  -80.133384,
  -80.143982,
  -80.132502,
  -80.230671,
  -80.235583,
  -80.184035,
  -80.1316858,
  -80.1876939,
  -80.186922,
  -80.189196,
  -80.1890455,
  -80.1949821,
  -80.1920305,
  -80.1951626,
  -80.1920722,
  -80.19159,
  -80.1839999,
  -80.1920503,
  -80.1246196,
  -80.1447683,
  -80.1424965,
  -80.140549,
  -80.132518,
  -80.19422,
  -80.14191],
 [4,
  4,
  4,
  6,
  4,
  5,
  3,
  4,
  2,
  4,
  4,
  4,
  5,
  2,
  4,
  5,
  3,
  1,
  4,
  5,
  5,
  6,
  6,
  3,
  6,
  5,
  0,
  1,
  5,
  2,
  3,
  3,
  6,
  1,
  2,
  2,
  0,
  6,
  6,
  5,
  2,
  1,
  3,
  7,
  24,
  6,
  10,
  7,
  4,
  5,
  7,
  1,
  0,
  8,
  18,
  5,
  11,
  1,
  8,
  5,
  2,
  2,
  4,
  5,
  7,
  0,
  12,
  13,
  4,
  10,
  3,
  10,
  2,
  7,
  12,
  11,
  2,
  5,
  1,
  5,
  16,
  13,
  10,
  14,
  6,
  1,
  3,
  5,
  6,
  2,
  3,
  6,
  3,
  11,
  2,
  1,
  1,
  0,
  4,
  6,
  4,
  7,
  5,
  8,
  3,
  6,
  0,
  0,
  3,
  9,
  4,
  6,
  7,
  1,
  10,
  1,
  10,
  5,
  1,
  5,
  11,
  1,
  3,
  4,
  8,
  8,
  4,
  7,
  6,
  2,
  8,
  6,
  6,
  1,
  2,
  3,
  0,
  0,
  7,
  3,
  3,
  1,
  2,
  10,
  6,
  6,
  2,
  5,
  4,
  3,
  4,
  4,
  2,
  1,
  3,
  2,
  2,
  2,
  5,
  11,
  1,
  3,
  4,
  1,
  1,
  2])

Put your parsed results into a DataFrame.

In [16]:
miami_bikes_df = pd.DataFrame({
    'latitude': latitude,
    'longitude': longitude,
    'bikes': bikes
})

miami_bikes_df.head()

    latitude  longitude  bikes
0  25.729275 -80.241581      4
1  25.732522 -80.233244      4
2  25.751100 -80.202641      4
3  25.760082 -80.196217      6
4  25.761884 -80.193101      4

In [10]:
#save miami_bikes_df as a csv file

miami_bikes_df.to_csv('../data/miami_bikes.csv', index=False)